### ISSUE TITLE
Compilation of RE

### ISSUE THREAD

**Issue by josecamachop** [josecamachop/FCParser#16]
It seems that compilation of RE that are going to be used frequently in a program is recommended in python. Then, we should compile the RE of the parser, instead of using re.search()

**Comment by jgarciagimenez** [comment]
There is some bug using compiled regular expresions. Example not working right now. I found that the issue is related to features with regular expression in structured sources, so the problem occur with the netflow part of the example.

**Comment by josecamachop** [comment]
Ok, I have been working mostly in the non-structural part, and this might have been the reason. In any case, I think we can reduce a lot code duplication, just by specifying "\n" as the structual separator. Then, all duplicated functions may disapear.
