### ISSUE TITLE
Add a flag for incremental features

### ISSUE THREAD

**Issue by josecamachop** [josecamachop/FCParser#21]
In case the intervals for the feature vectors span several input files, we want the output files to be incremental (if they exist, new counters are added to old ones). This can be misleading and we should have a flag in the config file to select the mode of operation (incremental or not)

**Comment by manjurvaz** [comment]
This issue was already solved on 19 Nov 2019 in branch 'revision': https://github.com/josecamachop/FCParser/commit/f73b93942e3f04c97255ec27874d80ccde50cebf
