### ISSUE TITLE
Use warnings or asserts to find config issues

### ISSUE THREAD

**Issue by josecamachop** [josecamachop/FCParser#22]
Currently, it is very hard to find when a config file is not consistent with the input data. A main challenge is to find when the separartor and Regular expressions are correct.

**Comment by manjurvaz** [comment]
General config. file and data source config. file validation has been improved in revision-v2 branch. Some incorrect implementations were fixed and the program is more "user-friendly", which makes it easier to find configuration errors. This new code was tested with some structured data sets but it is still pending to validate that the regular expressions are correct for unstructured data

**Comment by manjurvaz** [comment]
Debugging mode has been implemented in revision-v2 - https://github.com/josecamachop/FCParser/commit/7aac7afa7f03e906b5b3d168717678bc53ba72bb . By running fcparser with -d option, you can tell if regular expressions are correct by checking the displayed records (how the data is parsed into variables). Also, feature counters can be checked for each entry log.
