### ISSUE TITLE
Add reference to datetime in help information 

### ISSUE THREAD

**Issue by josecamachop** [josecamachop/FCParser#28]
Add reference to datetime in order to understand how the timestamp should be specified

https://docs.python.org/3/library/datetime.html

**Comment by manjurvaz** [comment]
Esto esta documentado en el manual referencia [2] y en el template 
source_config, no? O te refieres a otra cosa?

**Comment by manjurvaz** [comment]
A link with information about python datetime format is included at the top of the configuration templates as well as in the user manual (revision-v2 branch)
