### ISSUE TITLE
Close file pointers

### ISSUE THREAD

**Issue by josecamachop** [josecamachop/FCParser#8]
Hi,

Dumb question, don't we need to close files in python? because we do not close any...

**Comment by robertomagan** [comment]
Hi folk!

Could you give me an example? I suppose that you don't see the "close" reserved word anywhere, don't you? Instead, python uses the reserved word "with" for opening and closing files also even when something was wrong in reading, writing, etc. Of course, you can use common ways to do this with open() and close() code blocks.

Roberto.

**Comment by jgarciagimenez** [comment]
Hi, 
This was already fixed in the test branch. However, as the next release is delayed, it will be fixed in the current main branch soon.

**Comment by josecamachop** [comment]
Great, thanks, you know they say the day has 24 hours :-). In any case, I would work more on the branch, the issue is here and we can fix it in the future.
